version: '3.9'
services:
  cache:
    image: 'redis:7-alpine'
    container_name: bookkeeper_cache
    restart: always
    ports:
      - '6379:6379'
  db:
    image: 'postgres:14-alpine'
    container_name: bookkeeper_db
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: bookkeeper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'bookkeeper', '-U', 'postgres']
      retries: 3
      timeout: 5s
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    container_name: bookkeeper_adminer 
    restart: always
    ports:
      - '8080:8080'
volumes:
  db-data: